name: Backend CI

on:
  workflow_call:
  push:
    branches:
      - main
      - feature/*
    paths:
      - 'backend/**'
  pull_request:
    branches:
      - main
    paths:
      - 'backend/**'

concurrency:
  group: ${{ github.ref }}-backend-ci
  cancel-in-progress: true

jobs:
  lint:
    uses: ./.github/workflows/ruff.yaml

  backend-tests:
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: 'latest'

      - name: Sync deps (pyproject-first)
        run: |
          uv venv
          ./scripts/uv-sync.sh --all

      - name: Run pytest
        working-directory: ./backend/src
        run: |
          ../.venv/bin/python -m pytest
