name: Lint, format, and type-check
on:
  workflow_call:

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: latest

      - name: Sync deps (pyproject-first)
        run: |
          uv venv
          ./scripts/uv-sync.sh --all

      - name: Ruff lint
        run: .venv/bin/ruff check --output-format=github .

      - name: Ruff format (check only)
        run: .venv/bin/ruff format --check .

      - name: Ty type check (non-blocking)
        continue-on-error: true
        env:
          PYTHONPATH: backend/src:frontend/src:functions/src
        run: .venv/bin/ty check .
