name: Lint and format with Ruff
on:
  workflow_call:

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff==0.6.4
      - name: Run ruff
        run: |
          ruff check --output-format=github .
          ruff format --check .